Add failure demo
Adds
1. Client-side disconnect after 10ms on the 1st call to 'next()'.
2. Server-side delays 'next()' calls; combined with the client-side
   disconnect, this results in closing the scanner but being unable to
   send the exception response.
3. test.hbase provides table setup and a scan that requires open/next.

The server-side exception is CallerDisconnectedException, but it's never
logged with ALL logging enabled.

Running "scan 'test', {MAX_RESULT_SIZE => 10}" in 'hbase shell' returns
1 row instead of 2; add '-d' to see more detailed logs.

The failure scenario this is recreating is
1. Client sends an openScan request
2. server sends back scannerId and some rows
3. client sends request for more rows
4. before server sends response, client connection is closed (presumably
   by some sort of connection pool management); that causes
   RSRpcServices' scan to throw CallerDisconnectedException and close
   the scanner, which is not delivered to the client
5. client gets ConnectionClosedException, reopens the connection and
   retries the request
6. server sees scanner is closed and ignores it, sending an empty
   response (due to RSRpcServices.java line 3407)

The CallerDisconnectedException after adding relevant logging:

  org.apache.hadoop.hbase.ipc.CallerDisconnectedException: Aborting on region hbase:meta,,1.1588230740, call org.apache.hadoop.hbase.regionserver.ReversedRegionScannerImpl@7e0e17b7 after 0 ms, since caller disconnected
    at org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.nextInternal(HRegion.java:6754)
    at org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.nextRaw(HRegion.java:6601)
    at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:3243)
    at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:3488)
    at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42278)
    at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
    at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:139)
    at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
    at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)